const optionGender = [
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' },
    { value: 'Other', label: 'Other' }
]

const names = [
    'Khánh An',
    'Lan Chi',
    'Hoàng Diệp',
    'Ái Như',
    'Thục Khuê',
    'An Nhiên',
    'An Ngọc',
    'Thanh Thúy',
    'Thanh Hà',
    'Như Ý',
    'Minh Anh',
    'Quỳnh Anh',
    'Kim Dung',
    'Tâm Đoan',
    'Ngọc Hân',
    'Hồng Hạnh',
    'Quỳnh Nga',
    'Tuệ Nhi',
    'Minh Nguyệt',
    'Tuyết Minh',
    'Quỳnh Chi',
    'Hồng Nhung',
    'Minh Nguyệt',
    'Tuyết Lan',
    'Gia Linh',
    'Tuệ Mẫn',
    'Minh Khuê',
    'Tú Uyên',
    'Mẫn Nhi',
    'Tuệ Lâm',
    'Như Ý',
    'Minh Tuệ',
    'Thanh Vân',
    'Tuyết Lan',
    'Phương Linh',
    'Thu Nguyệt',
    'Nhã Kỳ',
    'Diên Vỹ',
    'Hoàng Oanh',
    'Hoàng Nguyên',
    'Nguyễn Văn Cường',
    'Trần Minh Hoàng',
    'Lê Quang Huy',
    'Phạm Anh Tuấn',
    'Vũ Đức Thắng',
    'Bùi Văn Nam',
    'Đỗ Thanh Tùng',
    'Nguyễn Hải Đăng',
    'Trần Quốc Khánh',
    'Lê Hữu Phúc',
    'Nguyễn Duy Khánh',
    'Đinh Văn Toàn',
    'Vũ Đức Long',
    'Phạm Thành Trung',
    'Hoàng Anh Dũng',
    'Nguyễn Tiến Mạnh',
    'Lê Thanh Sơn',
    'Trần Văn Kiên',
    'Đỗ Minh Hiếu',
    'Phạm Hoàng Nam',
    'Nguyễn Hữu Tài',
    'Trần Đức An',
    'Lê Quốc Bảo',
    'Nguyễn Văn Hòa',
    'Bùi Minh Quân',
    'Phạm Đức Huy',
    'Hoàng Văn Thái',
    'Vũ Tiến Đạt',
    'Nguyễn Văn Phúc',
    'Lê Đình Khoa'
]

export { optionGender, names }
